CREATE TABLE IF NOT EXISTS Categoria(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS Palabra(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre VARCHAR(30),
  imagen VARCHAR(30),
  categoriaId INTEGER REFERENCES Categoria
);

CREATE TABLE IF NOT EXISTS Nivel(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre VARCHAR(30),
  grado INTEGER
);

CREATE TABLE IF NOT EXISTS PalabrasNivel(
  palabra INTEGER REFERENCES Palabra,
  nivel INTEGER REFERENCES  Nivel,
  PRIMARY KEY (palabra, nivel)
);